version: '3'
services:
  app:
    build:
      context: ./docker/app
      args:
        DOCKER_UID: ${DOCKER_UID:-1000}
    volumes:
      - ./html:/var/www/html
    environment:
      - VIRTUAL_HOST=laravel-api.localhost
  db:
    build: ./docker/db
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker_db_user
      MYSQL_PASSWORD: docker_db_user_pass
      TZ: Asia/Tokyo
    volumes:
      - ./docker/db/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - VIRTUAL_HOST=pma.laravel-api.localhost
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
networks:
  default:
    external:
      name: nginx-proxy
